//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH
    {
        public int ID { get; set; }
        public string BatchID { get; set; }
        public Nullable<int> IntakeYear { get; set; }
        public string BatchOwnerID { get; set; }
    }
}
